/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wtf_NDKTools */

#ifndef _Included_com_example_wtf_NDKTools
#define _Included_com_example_wtf_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wtf_NDKTools
 * Method:    getIntFromNDK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_wtf_NDKTools_getIntFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
