/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wtf_InstanceMethodCall */

#ifndef _Included_com_example_wtf_InstanceMethodCall
#define _Included_com_example_wtf_InstanceMethodCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wtf_InstanceMethodCall
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_wtf_InstanceMethodCall_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
