/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wtf_getFromC */

#ifndef _Included_com_example_wtf_getFromC
#define _Included_com_example_wtf_getFromC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wtf_getFromC
 * Method:    getStringFromC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wtf_getFromC_getStringFromC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_wtf_getFromC
 * Method:    getIntegerFromC
 * Signature: (Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_example_wtf_getFromC_getIntegerFromC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_wtf_getFromC
 * Method:    getbooleanFromC
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_wtf_getFromC_getbooleanFromC
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_wtf_getFromC
 * Method:    getintFromC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wtf_getFromC_getintFromC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_wtf_getFromC
 * Method:    getbyteFromC
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_example_wtf_getFromC_getbyteFromC
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_example_wtf_getFromC
 * Method:    getlongFromC
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_wtf_getFromC_getlongFromC
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
