/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wtf_MMP */

#ifndef _Included_com_example_wtf_MMP
#define _Included_com_example_wtf_MMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wtf_MMP
 * Method:    getStringFromC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wtf_MMP_getStringFromC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_wtf_MMP
 * Method:    getintFromC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wtf_MMP_getintFromC
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
