/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wtf_ArrayTest */

#ifndef _Included_com_example_wtf_ArrayTest
#define _Included_com_example_wtf_ArrayTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wtf_ArrayTest
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_wtf_ArrayTest_intMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
